Buildroot: /home/some-user/src/junk/rpm_tries/autopkgtest-mv-c-project-1.0
Name: autopkgtest-mv-c-project
Version: 1.0
Release: 2
Summary: auto-generated package by debmake
License: see /usr/share/doc/autopkgtest-mv-c-project/copyright
Distribution: Debian
Group: Converted/local

%define _rpmdir ../
%define _rpmfilename %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm
%define _unpackaged_files_terminate_build 0

%description
This Debian binary package was auto-generated by the
debmake(1) command provided by the debmake package.


(Converted from a deb package by alien version 8.95.)

%files
%dir "/"
%dir "/usr/"
%dir "/usr/bin/"
"/usr/bin/autopkgtest-mv-c-project"
%dir "/usr/share/"
%dir "/usr/share/autopkgtest-mv-c-project/"
%dir "/usr/share/autopkgtest-mv-c-project/text/"
"/usr/share/autopkgtest-mv-c-project/text/hello.txt"
%dir "/usr/share/doc/"
%dir "/usr/share/doc/autopkgtest-mv-c-project/"
"/usr/share/doc/autopkgtest-mv-c-project/README.Debian"
"/usr/share/doc/autopkgtest-mv-c-project/README.md"
"/usr/share/doc/autopkgtest-mv-c-project/changelog.Debian.gz"
"/usr/share/doc/autopkgtest-mv-c-project/copyright"
%dir "/usr/share/info/"
"/usr/share/info/autopkgtest-mv-c-project.info.gz"
%dir "/usr/share/man/"
%dir "/usr/share/man/man1/"
"/usr/share/man/man1/autopkgtest-mv-c-project.1.gz"
