.TH [% project.package_to_variable_name_to_upper_case %] 1
.SH NAME
[% project.package_to_variable_name %] \- [% project.description %]
.\
.SH SYNOPSIS
.B [% project.package_to_variable_name %]
[ \fB\-a\fR \fIoption_1_value\fR ]
[ \fB\-\-option1=\fR\fIoption_1_value\fR ]
[ \fB\-b\fR \fIoption_2_value\fR ]
[ \fB\-\-option2=\fR\fIoption_2_value\fR ]
.IR file ...
.\
.SH DESCRIPTION
.B [% project.package_to_variable_name %]
Here is a longer description
.\
.SH RETURN VALUE
The
.BR [% project.package_to_variable_name %] ()
function returns a pointer to ...
.\
.SH SEE ALSO
.BR manpagename (7)
for more information about something else.
